#!/usr/bin/env python3
"""Content ingestion: content/<work>/… JSON  ->  SQL (idempotent upserts).

    python3 scripts/ingest.py                       # writes content/generated/*.sql
    python3 scripts/ingest.py --apply               # also applies to local DB
    python3 scripts/ingest.py --apply --db "$URI"   # apply to any Postgres (e.g. Supabase, service role)

Guarantees enforced here (in addition to DB constraints):
  * every edition references a rights row; rights with status pending/restricted
    cause the edition to be emitted as 'draft' (never published) — so nothing
    un-cleared can reach readers even if someone edits JSON carelessly.
  * verse text is validated (non-empty, refs match section, ordinals dense).
  * transliterations for Indian scripts are generated deterministically from
    the Devanagari base and stored as machine (is_machine=true) editions.
  * statements are emitted in chunked transactions (CHUNK_SIZE per transaction,
    default 400) with visible \\echo progress markers instead of one huge
    transaction — a single multi-thousand-statement transaction stalls through
    the pooler on large works. All statements are idempotent upserts, so a run
    interrupted between chunks resumes cleanly when re-run; ON_ERROR_STOP=1 at
    every call site keeps failures fatal.
"""
from __future__ import annotations
import argparse, glob, json, os, pathlib, subprocess, sys

sys.path.insert(0, os.path.dirname(__file__))
from translit import deva_to_script, LOSSY  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
OUT = CONTENT / "generated"

CLEARED = {"public_domain", "open_license", "permission_granted", "original"}

# Max statements per transaction in the emitted SQL. One huge transaction for a
# whole work (7k+ statements for the Gītā) is the deployment bottleneck: it
# holds a single pooler session for the entire run, gives no visible progress
# and, if killed near the end, loses all of it. Chunked transactions commit as
# they go (progress markers via \echo), and since every statement below is an
# idempotent upsert, an interrupted run can simply be re-run to resume.
CHUNK_SIZE = 400

# Valid enum values from supabase/migrations/0001_extensions_and_types.sql
VALID_PERSON_KIND = {"deity", "avatara", "sage", "king", "queen", "devotee", "demon", "author", "narrator", "other"}
VALID_PLACE_KIND = {"forest", "city", "river", "mountain", "tirtha", "loka", "kingdom", "other"}

def normalize_person_kind(k: str | None) -> str:
    k = k or "other"
    if k in VALID_PERSON_KIND:
        return k
    # Legacy bug: entity_kind 'person' was written as person_kind
    if k == "person":
        return "other"
    print(f"  ! unknown person_kind '{k}' -> 'other'", file=sys.stderr)
    return "other"

def normalize_place_kind(k: str | None) -> str:
    k = k or "other"
    if k in VALID_PLACE_KIND:
        return k
    # Legacy bug: 'field' is not a valid place_kind (Kurukshetra)
    if k == "field":
        return "tirtha"
    print(f"  ! unknown place_kind '{k}' -> 'other'", file=sys.stderr)
    return "other"


def q(v):
    """SQL literal."""
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (list, tuple)):
        return "array[" + ",".join(q(x) for x in v) + "]::text[]" if v else "'{}'::text[]"
    if isinstance(v, dict):
        return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


def jq(v):
    return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"


class Emitter:
    """Buffers statements and emits them as chunked transactions.

    Each chunk is wrapped in its own begin/commit (CHUNK_SIZE statements max)
    and preceded by a psql \\echo progress marker, so operators can see which
    chunk is being applied and where an interrupted run stopped. Every
    statement is an idempotent upsert, so re-running after an interruption
    resumes without duplicates or gaps.
    """

    def __init__(self, slug: str):
        self.slug = slug
        self.statements: list[str] = []

    def add(self, sql):
        self.statements.append(sql.strip().rstrip(";") + ";")

    def dump(self):
        total = len(self.statements)
        chunks = [self.statements[i:i + CHUNK_SIZE] for i in range(0, total, CHUNK_SIZE)]
        lines = [
            "-- GENERATED by scripts/ingest.py — do not edit by hand.",
            f"-- {total} statements in {len(chunks)} chunked transaction(s) of up to {CHUNK_SIZE} statements.",
            "-- Apply with: psql \"$DB_URL\" -v ON_ERROR_STOP=1 -q -f <this file>",
        ]
        for idx, chunk in enumerate(chunks, 1):
            lo = (idx - 1) * CHUNK_SIZE + 1
            hi = min(idx * CHUNK_SIZE, total)
            lines.append(f"\\echo '== {self.slug}: chunk {idx}/{len(chunks)} (statements {lo}-{hi} of {total})'")
            lines.append("begin;")
            lines.append("set local search_path = public;")
            lines.extend(chunk)
            lines.append("commit;")
        lines.append(f"\\echo '== {self.slug}: done — {total} statements in {len(chunks)} chunk(s)'")
        return "\n".join(lines) + "\n"


def ingest_work(work_dir: pathlib.Path, em: Emitter):
    work = json.loads((work_dir / "work.json").read_text(encoding="utf-8"))
    slug = work["slug"]

    # -- sources
    for s in work.get("sources", []):
        em.add(f"""
insert into sources (slug, kind, title, authors, publisher, year, edition_note, url, isbn, archive_url, notes)
values ({q(s['slug'])}, {q(s.get('kind','book'))}, {q(s['title'])}, {q(s.get('authors', []))}, {q(s.get('publisher'))},
        {q(s.get('year'))}, {q(s.get('edition_note'))}, {q(s.get('url'))}, {q(s.get('isbn'))}, {q(s.get('archive_url'))}, {q(s.get('notes'))})
on conflict (slug) do update set kind=excluded.kind, title=excluded.title, authors=excluded.authors, publisher=excluded.publisher,
  year=excluded.year, edition_note=excluded.edition_note, url=excluded.url, isbn=excluded.isbn, archive_url=excluded.archive_url, notes=excluded.notes""")

    # -- rights (keyed by (source, attribution_text) since no natural slug; we store key in notes)
    rights_status = {}
    for r in work.get("rights", []):
        rights_status[r["key"]] = r["status"]
        em.add(f"""
insert into rights (id, source_id, status, license, license_url, rights_holder, attribution_text, permission_document_url,
                    permission_granted_on, permission_expires_on, territory, allows_commercial, allows_derivatives, allows_audio, notes)
values (rights_key_uuid({q(slug + ':' + r['key'])}), (select id from sources where slug = {q(r['source'])}), {q(r['status'])}::rights_status,
        {q(r.get('license'))}, {q(r.get('license_url'))}, {q(r.get('rights_holder'))}, {q(r['attribution_text'])}, {q(r.get('permission_document_url'))},
        {q(r.get('permission_granted_on'))}, {q(r.get('permission_expires_on'))}, {q(r.get('territory','worldwide'))},
        {q(r.get('allows_commercial', False))}, {q(r.get('allows_derivatives', False))}, {q(r.get('allows_audio', False))}, {q('key=' + r['key'])})
on conflict (id) do update set source_id=excluded.source_id, status=excluded.status, license=excluded.license, license_url=excluded.license_url,
  rights_holder=excluded.rights_holder, attribution_text=excluded.attribution_text, permission_document_url=excluded.permission_document_url,
  permission_granted_on=excluded.permission_granted_on, permission_expires_on=excluded.permission_expires_on, territory=excluded.territory,
  allows_commercial=excluded.allows_commercial, allows_derivatives=excluded.allows_derivatives, allows_audio=excluded.allows_audio, notes=excluded.notes""")

    # -- work
    em.add(f"""
insert into works (slug, short_code, title_iast, title_sa, tradition, original_language, original_script, structure, description, status, metadata)
values ({q(slug)}, {q(work['short_code'])}, {q(work['title_iast'])}, {q(work['title_sa'])}, {q(work.get('tradition'))},
        {q(work['original_language'])}, {q(work['original_script'])}, {jq(work.get('structure', []))}, {q(work.get('description'))}, 'published', {jq(work.get('metadata', {}))})
on conflict (slug) do update set short_code=excluded.short_code, title_iast=excluded.title_iast, title_sa=excluded.title_sa, tradition=excluded.tradition,
  original_language=excluded.original_language, original_script=excluded.original_script, structure=excluded.structure, description=excluded.description,
  status='published', metadata=excluded.metadata""")

    # -- editions
    editions = {e["slug"]: e for e in work["editions"]}
    for e in work["editions"]:
        st = rights_status.get(e["rights"])
        if st is None:
            raise SystemExit(f"edition {e['slug']} references unknown rights key {e['rights']}")
        status = "published" if st in CLEARED else "draft"
        if st not in CLEARED:
            print(f"  ! edition {e['slug']} has rights status {st}: emitted as DRAFT (not servable)")
        em.add(f"""
insert into editions (work_id, slug, kind, language_code, script_code, title, contributors, source_id, rights_id, derived_from, is_default, is_machine, status, sort_order, description, metadata)
values ((select id from works where slug={q(slug)}), {q(e['slug'])}, {q(e['kind'])}::edition_kind, {q(e['language_code'])}, {q(e['script_code'])}, {q(e['title'])},
        {q(e.get('contributors', []))}, (select id from sources where slug={q(e.get('source'))}), rights_key_uuid({q(slug + ':' + e['rights'])}),
        (select id from editions where slug={q(e.get('derived_from'))}), {q(e.get('is_default', False))}, {q(e.get('is_machine', False))},
        {q(status)}::publish_status, {q(e.get('sort_order', 100))}, {q(e.get('description'))}, {jq(e.get('metadata', {}))})
on conflict (slug) do update set kind=excluded.kind, language_code=excluded.language_code, script_code=excluded.script_code, title=excluded.title,
  contributors=excluded.contributors, source_id=excluded.source_id, rights_id=excluded.rights_id, derived_from=excluded.derived_from,
  is_default=excluded.is_default, is_machine=excluded.is_machine, status=excluded.status, sort_order=excluded.sort_order, description=excluded.description, metadata=excluded.metadata""")

    # -- graph entities (before verses, so speakers resolve)
    gpath = work_dir / "graph.json"
    graph = json.loads(gpath.read_text(encoding="utf-8")) if gpath.exists() else {}
    for p in graph.get("people", []):
        em.add(f"""
insert into people (slug, kind, name_iast, name_sa, epithets, gender, description, status)
values ({q(p['slug'])}, {q(normalize_person_kind(p.get('kind')))}::person_kind, {q(p['name_iast'])}, {q(p['name_sa'])}, {q(p.get('epithets', []))}, {q(p.get('gender'))}, {q(p.get('description'))}, 'published')
on conflict (slug) do update set kind=excluded.kind, name_iast=excluded.name_iast, name_sa=excluded.name_sa, epithets=excluded.epithets, gender=excluded.gender, description=excluded.description, status='published'""")
        emit_names(em, "person", "people", p)
    for p in graph.get("places", []):
        em.add(f"""
insert into places (slug, kind, name_iast, name_sa, alt_names, description, modern_name, latitude, longitude, status)
values ({q(p['slug'])}, {q(normalize_place_kind(p.get('kind')))}::place_kind, {q(p['name_iast'])}, {q(p['name_sa'])}, {q(p.get('alt_names', []))}, {q(p.get('description'))}, {q(p.get('modern_name'))}, {q(p.get('latitude'))}, {q(p.get('longitude'))}, 'published')
on conflict (slug) do update set kind=excluded.kind, name_iast=excluded.name_iast, name_sa=excluded.name_sa, alt_names=excluded.alt_names, description=excluded.description, modern_name=excluded.modern_name, latitude=excluded.latitude, longitude=excluded.longitude, status='published'""")
        emit_names(em, "place", "places", p)
    for t in graph.get("topics", []):
        em.add(f"""
insert into topics (slug, name_iast, name_sa, description, status)
values ({q(t['slug'])}, {q(t['name_iast'])}, {q(t.get('name_sa'))}, {q(t.get('description'))}, 'published')
on conflict (slug) do update set name_iast=excluded.name_iast, name_sa=excluded.name_sa, description=excluded.description, status='published'""")
        emit_names(em, "topic", "topics", t)

    # -- sections + verses (generic: supports Bhāgavata 2-level canto→chapter and Gītā 1-level chapter)
    verse_files = sorted(glob.glob(str(work_dir / "**" / "verses.json"), recursive=True))
    # Pre-compute generic edition slugs for rendering (per-work, not hardcoded sb-*)
    def _find_edition(pred):
        for eslug, e in editions.items():
            if pred(e):
                return eslug
        return None
    base_deva_slug = _find_edition(lambda e: e.get("kind") == "base_text" and e.get("language_code") == "sa" and e.get("script_code") == "Deva")
    iast_slug = _find_edition(lambda e: e.get("kind") == "transliteration" and e.get("language_code") == "sa" and e.get("script_code") == "Latn" and not e.get("is_machine"))
    en_slug = _find_edition(lambda e: e.get("kind") == "translation" and e.get("language_code") == "en")
    ml_slug = _find_edition(lambda e: e.get("kind") == "translation" and e.get("language_code") == "ml")
    # Every word-by-word edition reads its own verse field (`content_field`), so
    # adding a second word-by-word source is additive and can never overwrite an
    # existing one.
    wm_editions = [(eslug, e.get("content_field", "word_meanings"))
                   for eslug, e in editions.items() if e.get("kind") == "word_meanings"]
    all_xrefs = []
    n_verses = 0
    for vf in verse_files:
        data = json.loads(pathlib.Path(vf).read_text(encoding="utf-8"))
        sec = data["section"]
        # Determine section handling: 2-level (canto+chapter) vs 1-level (chapter only)
        if "canto" in sec and "chapter" in sec:
            canto, chap = sec["canto"], sec["chapter"]
            em.add(f"""
insert into sections (work_id, parent_id, level, ordinal, ref, title_iast, title_sa, status)
values ((select id from works where slug={q(slug)}), null, 1, {canto['ordinal']}, {q(canto['ref'])}, {q(canto.get('title_iast'))}, {q(canto.get('title_sa'))}, 'published')
on conflict (work_id, ref) do update set title_iast=excluded.title_iast, title_sa=excluded.title_sa, ordinal=excluded.ordinal, status='published'""")
            em.add(f"""
insert into sections (work_id, parent_id, level, ordinal, ref, title_iast, title_sa, summary, status, metadata)
values ((select id from works where slug={q(slug)}), (select id from sections where work_id=(select id from works where slug={q(slug)}) and ref={q(canto['ref'])}),
        2, {chap['ordinal']}, {q(chap['ref'])}, {q(chap.get('title_iast'))}, {q(chap.get('title_sa'))}, {q(chap.get('summary_en'))}, 'published',
        {jq({k: v for k, v in chap.items() if k not in ('ref', 'ordinal')})})
on conflict (work_id, ref) do update set title_iast=excluded.title_iast, title_sa=excluded.title_sa, summary=excluded.summary, ordinal=excluded.ordinal, parent_id=excluded.parent_id, status='published', metadata=excluded.metadata""")
            chapter_ref = chap["ref"]
            chapter_obj = chap
        elif "chapter" in sec and "canto" not in sec:
            chap = sec["chapter"]
            em.add(f"""
insert into sections (work_id, parent_id, level, ordinal, ref, title_iast, title_sa, summary, status, metadata)
values ((select id from works where slug={q(slug)}), null,
        1, {chap['ordinal']}, {q(chap['ref'])}, {q(chap.get('title_iast'))}, {q(chap.get('title_sa'))}, {q(chap.get('summary_en'))}, 'published',
        {jq({k: v for k, v in chap.items() if k not in ('ref', 'ordinal')})})
on conflict (work_id, ref) do update set title_iast=excluded.title_iast, title_sa=excluded.title_sa, summary=excluded.summary, ordinal=excluded.ordinal, parent_id=excluded.parent_id, status='published', metadata=excluded.metadata""")
            chapter_ref = chap["ref"]
            chapter_obj = chap
        else:
            raise SystemExit(f"section structure not recognised in {vf}: {list(sec.keys())} — expected canto+chapter (Bhāgavata) or chapter only (Gītā)")
        # section-level localized titles (generic: find translation editions by language)
        for lang, key in (("en", "title_en"), ("ml", "title_ml")):
            if chapter_obj.get(key):
                ed = en_slug if lang == "en" else ml_slug
                if ed:
                    em.add(f"""
insert into section_contents (section_id, edition_id, title, summary, status)
values ((select id from sections where ref={q(chapter_ref)} and work_id=(select id from works where slug={q(slug)})), (select id from editions where slug={q(ed)}), {q(chapter_obj[key])}, {q(chapter_obj.get('summary_' + lang))}, 'published')
on conflict (section_id, edition_id) do update set title=excluded.title, summary=excluded.summary, status='published'""")

        prev = 0
        for v in data["verses"]:
            assert v["ref"].startswith(chapter_ref + "."), f"{v['ref']} not in {chapter_ref} (file {vf})"
            assert v["ordinal"] == prev + 1, f"non-dense ordinal at {v['ref']} (expected {prev+1})"
            prev = v["ordinal"]
            n_verses += 1
            assert v["deva"].strip() and v["iast"].strip(), f"empty base text at {v['ref']}"
            verse_meta = dict(v.get("metadata") or {})
            em.add(f"""
insert into verses (work_id, section_id, ordinal, ref, kind, meter, speaker_id, status, metadata)
values ((select id from works where slug={q(slug)}), (select id from sections where ref={q(chapter_ref)} and work_id=(select id from works where slug={q(slug)})),
        {v['ordinal']}, {q(v['ref'])}, {q(v.get('kind','verse'))}::verse_kind, {q(v.get('meter'))}, (select id from people where slug={q(v.get('speaker'))}), 'published', {jq(verse_meta)})
on conflict (work_id, ref) do update set ordinal=excluded.ordinal, kind=excluded.kind, meter=excluded.meter, speaker_id=excluded.speaker_id, section_id=excluded.section_id, status='published', metadata=coalesce(verses.metadata,'{{}}'::jsonb) || excluded.metadata""")

            # Generic renderings: map deva/iast/en/ml via discovered edition slugs (not hardcoded sb-*)
            renderings = {}
            if base_deva_slug:
                renderings[base_deva_slug] = v["deva"]
            if iast_slug:
                renderings[iast_slug] = v["iast"]
            if en_slug and v.get("en"):
                renderings[en_slug] = v["en"]
            if ml_slug and v.get("ml"):
                renderings[ml_slug] = v["ml"]
            # machine transliterations of the Devanagari base into other Indic scripts
            for eslug, e in editions.items():
                if e.get("is_machine") and e["kind"] == "transliteration" and e.get("derived_from"):
                    if e["derived_from"] == base_deva_slug:
                        renderings[eslug] = deva_to_script(v["deva"], e["script_code"])
            for eslug, body in renderings.items():
                if not body:
                    continue
                notes = v.get("notes_en") if eslug == en_slug else None
                if eslug in editions and editions[eslug].get("is_machine") and editions[eslug]["script_code"] in LOSSY:
                    notes = "Automatic conversion; this script cannot represent every Sanskrit sound distinctly."
                emit_content(em, slug, v["ref"], eslug, body, notes=notes)
            for wm_slug, wm_field in wm_editions:
                rows = v.get(wm_field)
                if rows and (wm_slug in editions or slug == "bhagavata-purana"):
                    emit_content(em, slug, v["ref"], wm_slug,
                                 "\n".join(f"{w['word']} — {w['meaning']}" for w in rows),
                                 word_meanings=rows)

            for m in v.get("mentions", []):
                table = {"person": "people", "place": "places", "topic": "topics", "story": "stories"}[m["kind"]]
                if m["kind"] == "story":
                    continue  # stories inserted after verses; mentions emitted below
                em.add(f"""
insert into verse_mentions (verse_id, entity_kind, entity_id, role, surface_form, status)
values ((select id from verses where ref={q(v['ref'])} and work_id=(select id from works where slug={q(slug)})), {q(m['kind'])}::entity_kind,
        (select id from {table} where slug={q(m['slug'])}), {q(m.get('role'))}, {q(m.get('surface_form'))}, 'published')
on conflict (verse_id, entity_kind, entity_id, role) do update set surface_form=excluded.surface_form, status='published'""")
            for x in v.get("xrefs", []):
                all_xrefs.append((v["ref"], x))
        em.add(f"""update sections set verse_count = (select count(*) from verses where section_id = sections.id)
where work_id = (select id from works where slug={q(slug)})""")

    declared = (work.get("metadata") or {}).get("imported_verse_count")
    if declared is None:
        declared = (work.get("metadata") or {}).get("total_verses")
    if declared is not None and n_verses != declared:
        raise SystemExit(
            f"{slug}: JSON has {n_verses} verses but work.json declares {declared}"
        )

    # -- stories (need verses for ranges), story mentions, relations
    for s in graph.get("stories", []):
        em.add(f"""
insert into stories (slug, work_id, title_iast, title_sa, summary, start_verse_id, end_verse_id, narrator_id, place_id, status)
values ({q(s['slug'])}, (select id from works where slug={q(slug)}), {q(s['title_iast'])}, {q(s.get('title_sa'))}, {q(s.get('summary'))},
        (select id from verses where ref={q(s.get('start'))} and work_id=(select id from works where slug={q(slug)})),
        (select id from verses where ref={q(s.get('end'))} and work_id=(select id from works where slug={q(slug)})),
        (select id from people where slug={q(s.get('narrator'))}), (select id from places where slug={q(s.get('place'))}), 'published')
on conflict (slug) do update set title_iast=excluded.title_iast, title_sa=excluded.title_sa, summary=excluded.summary, start_verse_id=excluded.start_verse_id,
  end_verse_id=excluded.end_verse_id, narrator_id=excluded.narrator_id, place_id=excluded.place_id, status='published'""")
        emit_names(em, "story", "stories", s)
    for vf in verse_files:
        data = json.loads(pathlib.Path(vf).read_text(encoding="utf-8"))
        for v in data["verses"]:
            for m in v.get("mentions", []):
                if m["kind"] != "story":
                    continue
                em.add(f"""
insert into verse_mentions (verse_id, entity_kind, entity_id, role, surface_form, status)
values ((select id from verses where ref={q(v['ref'])} and work_id=(select id from works where slug={q(slug)})), 'story'::entity_kind,
        (select id from stories where slug={q(m['slug'])}), {q(m.get('role'))}, {q(m.get('surface_form'))}, 'published')
on conflict (verse_id, entity_kind, entity_id, role) do update set surface_form=excluded.surface_form, status='published'""")

    tables = {"person": "people", "place": "places", "topic": "topics", "story": "stories", "work": "works"}
    for r in graph.get("relations", []):
        fk, fs = r["from"]; tk, ts = r["to"]
        em.add(f"""
insert into entity_relations (from_kind, from_id, relation, to_kind, to_id, note, status)
values ({q(fk)}::entity_kind, (select id from {tables[fk]} where slug={q(fs)}), {q(r['relation'])}, {q(tk)}::entity_kind, (select id from {tables[tk]} where slug={q(ts)}), {q(r.get('note'))}, 'published')
on conflict (from_kind, from_id, relation, to_kind, to_id) do update set note=excluded.note, status='published'""")

    # -- cross references (only when the target verse exists; targets outside the pilot are kept as pending metadata)
    for from_ref, x in all_xrefs:
        em.add(f"""
insert into cross_references (from_verse_id, to_verse_id, kind, note, status)
select f.id, t.id, {q(x.get('kind','see_also'))}::xref_kind, {q(x.get('note'))}, 'published'
  from verses f, verses t
 where f.work_id=(select id from works where slug={q(slug)}) and f.ref={q(from_ref)}
   and t.work_id = f.work_id and t.ref={q(x['to'])}
on conflict (from_verse_id, to_verse_id, kind) do update set note=excluded.note, status='published'""")
        # store unresolved xrefs in verse metadata so they surface when target verses are added
        em.add(f"""
update verses set metadata = jsonb_set(coalesce(metadata,'{{}}'::jsonb), '{{pending_xrefs}}',
  coalesce(metadata->'pending_xrefs','[]'::jsonb) || {jq({'to': x['to'], 'kind': x.get('kind', 'see_also'), 'note': x.get('note')})})
 where work_id=(select id from works where slug={q(slug)}) and ref={q(from_ref)}
   and not exists (select 1 from verses t where t.work_id = verses.work_id and t.ref = {q(x['to'])})
   and not (coalesce(metadata->'pending_xrefs','[]'::jsonb) @> {jq([{'to': x['to']}])})""")


def emit_names(em, kind, table, ent):
    for lang, name in (ent.get("names") or {}).items():
        script = {"en": "Latn", "ml": "Mlym", "hi": "Deva", "sa": "Deva", "kn": "Knda", "te": "Telu", "ta": "Taml", "bn": "Beng", "gu": "Gujr"}[lang]
        em.add(f"""
insert into entity_names (entity_kind, entity_id, language_code, script_code, name, is_primary)
values ({q(kind)}::entity_kind, (select id from {table} where slug={q(ent['slug'])}), {q(lang)}, {q(script)}, {q(name)}, true)
on conflict (entity_kind, entity_id, language_code, script_code, name) do nothing""")
    # IAST + Devanagari names from the entity itself
    for lang, script, key in (("sa", "Latn", "name_iast"), ("sa", "Deva", "name_sa"), ("sa", "Latn", "title_iast"), ("sa", "Deva", "title_sa")):
        if ent.get(key):
            em.add(f"""
insert into entity_names (entity_kind, entity_id, language_code, script_code, name, is_primary)
values ({q(kind)}::entity_kind, (select id from {table} where slug={q(ent['slug'])}), {q(lang)}, {q(script)}, {q(ent[key])}, true)
on conflict (entity_kind, entity_id, language_code, script_code, name) do nothing""")


def emit_content(em, work_slug, ref, edition_slug, body, notes=None, word_meanings=None):
    em.add(f"""
insert into verse_contents (verse_id, edition_id, body, word_meanings, notes, status)
values ((select id from verses where ref={q(ref)} and work_id=(select id from works where slug={q(work_slug)})), (select id from editions where slug={q(edition_slug)}),
        {q(body)}, {jq(word_meanings) if word_meanings else 'null'}, {q(notes)}, 'published')
on conflict (verse_id, edition_id) do update set body=excluded.body, word_meanings=excluded.word_meanings, notes=excluded.notes, status='published'""")


HELPERS = """
-- deterministic uuid for rights rows keyed by '<work>:<key>' (uuid v5-ish via md5)
create or replace function public.rights_key_uuid(k text) returns uuid language sql immutable as $$
  select md5('dharma-library:rights:' || k)::uuid
$$;
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--db", help="postgres URI (default: local pgserver)")
    a = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    for wj in sorted(glob.glob(str(CONTENT / "*" / "work.json"))):
        wd = pathlib.Path(wj).parent
        em = Emitter(wd.name)
        em.add(HELPERS)
        print("== ingest", wd.name)
        ingest_work(wd, em)
        outp = OUT / f"{wd.name}.sql"
        outp.write_text(em.dump(), encoding="utf-8")
        print("   wrote", outp.relative_to(ROOT))
        if a.apply:
            uri = a.db
            if not uri:
                sys.path.insert(0, str(ROOT / "scripts"))
                import localdb  # type: ignore
                uri = localdb.db_uri(localdb.server())
                psql = localdb.psql_bin()
            else:
                psql = "psql"
            r = subprocess.run([psql, uri, "-v", "ON_ERROR_STOP=1", "-q", "-f", str(outp)], capture_output=True, text=True)
            if r.returncode != 0:
                print(r.stderr)
                raise SystemExit("apply failed")
            print("   applied")


if __name__ == "__main__":
    main()
