-- =============================================================================
-- Dharma Library — 0008: Storage RLS Policies (intentionally no-op)
-- =============================================================================
-- Historical note:
--   Earlier versions of this migration mutated the Supabase-owned `storage`
--   schema: they inserted into `storage.buckets` and did
--   `ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY` plus 5 policies
--   on `storage.objects`. The `storage` schema is owned by Supabase and is
--   managed declaratively via `supabase/config.toml` (`[storage.buckets.*]`)
--   and the Storage API — not via migrations. `supabase db push` fails (and
--   should not) when a migration tries to take ownership of `storage.objects`.
--
-- Current approach:
--   * Buckets ('audio', 'rights-documents') are declared in
--     `supabase/config.toml` and created by `supabase start` / `supabase db
--     push`'s declarative storage config.
--   * Storage RLS policies, if customisation is needed, should be managed
--     outside migrations (Supabase dashboard / Storage API) or via the
--     declarative storage config — never by `ALTER TABLE storage.objects` in
--     a migration.
--
-- This file is kept as a no-op to preserve migration history linearity.
-- `supabase db push` and the CI harness (`psql -f supabase/migrations/*.sql`)
-- both require every `*.sql` in this directory to be valid SQL.
-- =============================================================================

-- No-op: intentionally does NOT alter Supabase-owned `storage.objects` or
-- `storage.buckets`. See `supabase/config.toml` for bucket declarations.
SELECT 1;
